using System.Text;
using Agelos.Cli.Models;
using Agelos.Cli.Services;
using Spectre.Console;

namespace Agelos.Cli.Core;

public interface IContainerBuilder
{
    Task<string> BuildCustomImageAsync(
        string agent,
        RuntimeRequirements runtimes,
        IReadOnlyList<string>? addOns,
        IContainerRuntime runtime,
        CancellationToken cancellationToken = default);

    string GenerateImageTag(string agent, RuntimeRequirements runtimes, IReadOnlyList<string>? addOns = null);
}

public class ContainerBuilder : IContainerBuilder
{
    private readonly IFileService _fileService;

    public ContainerBuilder(IFileService fileService) => _fileService = fileService;

    public async Task<string> BuildCustomImageAsync(
        string agent,
        RuntimeRequirements runtimes,
        IReadOnlyList<string>? addOns,
        IContainerRuntime runtime,
        CancellationToken cancellationToken = default)
    {
        var imageTag = GenerateImageTag(agent, runtimes, addOns);

        if (await runtime.ImageExistsAsync(imageTag, cancellationToken))
        {
            AnsiConsole.MarkupLine($"[dim]Image {imageTag} already exists (cached)[/]");
            return imageTag;
        }

        AnsiConsole.MarkupLine($"[yellow]Building custom image: {imageTag}[/]");

        var dockerfile = GenerateDockerfile(agent, runtimes, addOns);
        var buildDir = Path.Combine(Path.GetTempPath(), $"agelos-build-{Guid.NewGuid():N}");
        await _fileService.CreateDirectoryAsync(buildDir);
        var dockerfilePath = Path.Combine(buildDir, "Dockerfile");
        await _fileService.WriteAllTextAsync(dockerfilePath, dockerfile);

        try
        {
            await runtime.BuildAsync(new BuildOptions
            {
                Dockerfile = dockerfilePath,
                Context = buildDir,
                Tag = imageTag
            }, cancellationToken);

            AnsiConsole.MarkupLine($"[green]Built {imageTag}[/]");
            return imageTag;
        }
        finally
        {
            if (Directory.Exists(buildDir))
                Directory.Delete(buildDir, recursive: true);
        }
    }

    public string GenerateImageTag(string agent, RuntimeRequirements runtimes, IReadOnlyList<string>? addOns = null)
    {
        var parts = new List<string> { agent };

        if (runtimes.DotNet?.Any() == true)
            parts.Add($"dotnet{string.Join("-", runtimes.DotNet)}");

        if (runtimes.Node != null)
            parts.Add($"node{runtimes.Node}");

        if (runtimes.Python != null)
            parts.Add($"py{runtimes.Python.Replace(".", "")}");

        if (runtimes.Go != null)
            parts.Add($"go{runtimes.Go.Replace(".", "")}");

        if (runtimes.Rust)
            parts.Add("rust");

        if (runtimes.Custom?.Any() == true)
            foreach (var c in runtimes.Custom)
                parts.Add($"{c.Name}{c.Version.Replace(".", "")}");

        if (addOns?.Any() == true)
            foreach (var a in addOns)
                parts.Add(a);

        return $"agelos/{string.Join("-", parts)}";
    }

    private string GenerateDockerfile(string agent, RuntimeRequirements runtimes, IReadOnlyList<string>? addOns)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by Agentz");
        sb.AppendLine("FROM alpine:3.21");
        sb.AppendLine();
        sb.AppendLine("RUN apk add --no-cache \\");
        sb.AppendLine("    bash curl wget git ca-certificates gnupg \\");
        sb.AppendLine("    build-base unzip libgcc libstdc++ gcompat");
        sb.AppendLine();

        if (runtimes.DotNet?.Any() == true)
        {
            sb.AppendLine($"# .NET SDK ({string.Join(", ", runtimes.DotNet)})");
            sb.AppendLine("RUN apk add --no-cache icu-libs krb5-libs libssl3 zlib");
            foreach (var v in runtimes.DotNet)
            {
                sb.AppendLine($"RUN curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- " +
                              $"--channel {v}.0 --install-dir /usr/local/dotnet");
            }
            sb.AppendLine("ENV PATH=\"/usr/local/dotnet:$PATH\"");
            sb.AppendLine("ENV DOTNET_ROOT=\"/usr/local/dotnet\"");
            sb.AppendLine();
        }

        if (runtimes.Node != null)
        {
            sb.AppendLine($"# Node.js {runtimes.Node}");
            sb.AppendLine($"RUN apk add --no-cache \"nodejs~={runtimes.Node}\" npm");
            sb.AppendLine();
        }

        if (runtimes.Python != null)
        {
            sb.AppendLine($"# Python {runtimes.Python}");
            sb.AppendLine("RUN apk add --no-cache python3 py3-pip");
            sb.AppendLine();
        }

        if (runtimes.Go != null)
        {
            sb.AppendLine($"# Go {runtimes.Go}");
            sb.AppendLine($"RUN wget -q https://go.dev/dl/go{runtimes.Go}.linux-amd64.tar.gz \\");
            sb.AppendLine($"    && tar -C /usr/local -xzf go{runtimes.Go}.linux-amd64.tar.gz \\");
            sb.AppendLine($"    && rm go{runtimes.Go}.linux-amd64.tar.gz");
            sb.AppendLine("ENV PATH=\"/usr/local/go/bin:$PATH\"");
            sb.AppendLine();
        }

        if (runtimes.Rust)
        {
            sb.AppendLine("# Rust");
            sb.AppendLine("RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y");
            sb.AppendLine("ENV PATH=\"/root/.cargo/bin:$PATH\"");
            sb.AppendLine();
        }

        if (runtimes.Custom?.Any() == true)
        {
            foreach (var c in runtimes.Custom)
            {
                sb.AppendLine($"# {c.Name} {c.Version}");
                sb.AppendLine($"RUN {c.InstallScript}");
                sb.AppendLine();
            }
        }

        sb.AppendLine("# Non-root user");
        sb.AppendLine("RUN adduser -D codeuser \\");
        sb.AppendLine("    && mkdir -p /home/codeuser/.local/state /home/codeuser/.config /workspace \\");
        sb.AppendLine("    && chown -R codeuser:codeuser /home/codeuser /workspace");
        sb.AppendLine();

        sb.Append(GetAgentSetup(agent));
        sb.Append(GetAddOnSetup(addOns));

        sb.AppendLine("WORKDIR /workspace");
        sb.AppendLine("USER codeuser");
        sb.AppendLine();
        sb.AppendLine(GetAgentCmd(agent));

        return sb.ToString();
    }

    private static string GetAgentSetup(string agent) => agent switch
    {
        "opencode" =>
            "# OpenCode\n" +
            "RUN apk add --no-cache nodejs npm\n" +
            "ENV BUN_INSTALL=\"/usr/local\"\n" +
            "RUN curl -fsSL https://bun.sh/install | bash\n" +
            "RUN /usr/local/bin/bun add -g opencode-ai\n",
        "aider" =>
            "# Aider\n" +
            "RUN apk add --no-cache python3 py3-pip && pip3 install --break-system-packages aider-chat\n",
        _ => "# No agent-specific setup\n"
    };

    private static string GetAddOnSetup(IReadOnlyList<string>? addOns)
    {
        if (addOns == null || addOns.Count == 0) return string.Empty;

        var sb = new StringBuilder();
        foreach (var addOn in addOns)
        {
            if (addOn == "llama-cpp")
                sb.Append(
                    "# llama.cpp\n" +
                    "RUN git clone https://github.com/ggerganov/llama.cpp /opt/llama.cpp \\\n" +
                    "    && cd /opt/llama.cpp && make\n" +
                    "ENV PATH=\"/opt/llama.cpp:$PATH\"\n");
        }
        return sb.ToString();
    }

    private static string GetAgentCmd(string agent) => agent switch
    {
        "opencode" => "CMD [\"opencode\"]",
        "aider"    => "CMD [\"aider\"]",
        _          => "CMD [\"/bin/bash\"]"
    };
}
